apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-demo-springboot
  template:
    metadata:
      labels:
        app: jenkins-demo-springboot
    spec:
      containers:
      - name: jenkins-demo-springboot
        image: 172.16.195.111/library/jenkins-demo-springboot:<BUILD_TAG>
        # command: [ "sh", "-c", "java $(JVMSIZE) -Dserver.port=8001 -jar /app/app.jar"]
        # command: [ "sh", "-c", "java $(JVMSIZE) -jar /app/app.jar" --server.port=8001]
        env:
        - name: JVMSIZE
          value: -Xms512m -Xmx1g -Djava.security.egd=file:/dev/./urandom
        # - name: LOGPATH
        #   value: -Dlogging.path=/logs/mmd/mall-page/
        # - name: EUREKA
        #   value: -DEUREKA_SERVER_ADDRESS=http://eureka-service1.k8s.maimaiti.site/eureka/
        # - name: APOLLO
        #   value: -Dapollo.meta=http://devconf.maimaiti.site:8001
        ports:
        - containerPort: 8001
        resources:
          requests:
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-demo-springboot
spec:
  selector:
    app: jenkins-demo-springboot
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-demo-springboot
spec:
  rules:
  - host: jenkins-demo-springboot.172.16.195.210.xip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-demo-springboot
            port:
              number: 8001
